# Generated by Django 5.2.6 on 2025-11-25 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtrackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='labassistanttable',
            name='department',
        ),
        migrations.AddField(
            model_name='labassistanttable',
            name='LABID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtrackapp.labtable'),
        ),
    ]
