# Generated by Django 5.2.6 on 2025-11-25 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtrackapp', '0002_labtable_remove_labassistanttable_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmanagertable',
            name='LABID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtrackapp.labtable'),
        ),
    ]
