# Generated by Django 5.2.6 on 2025-11-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labtrackapp', '0003_labmanagertable_labid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labmanagertable',
            name='department',
        ),
    ]
