# Generated by Django 5.2.6 on 2025-12-31 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtrackapp', '0004_remove_labmanagertable_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlabassigntable',
            name='lab',
        ),
        migrations.AddField(
            model_name='studentlabassigntable',
            name='LABID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtrackapp.labtable'),
        ),
    ]
