# Generated by Django 5.2.6 on 2025-12-31 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtrackapp', '0005_remove_studentlabassigntable_lab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labassigntable',
            name='lab',
        ),
        migrations.AddField(
            model_name='labassigntable',
            name='LABID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='labtrackapp.labtable'),
        ),
        migrations.AddField(
            model_name='studentlabassigntable',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
