# Generated by Django 5.2.6 on 2025-12-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtrackapp', '0006_remove_labassigntable_lab_labassigntable_labid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktable',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
