# Generated by Django 5.2.6 on 2026-01-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtrackapp', '0007_tasktable_date_tasktable_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='Class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
